name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.1
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Byte compile
      run: make
    - name: Try the server
      run: |
        emacs --daemon -L . -l elisp-docstring-server
        emacsclient --eval '(elisp-docstring-server-start)'
        curl 'http://localhost:3000/api/describe-symbol?symbol=car'
    # - name: Run Tests
    #   run: emacs -Q --batch -L . -l elisp-docstring-server-tests -f ert-run-tests-batch-and-exit
